wallpaper {
    monitor = eDP-2
    path = /home/shadow_angel/Pictures/Wallpapers/wallpaper.jpg
    fit_mode = cover
}
wallpaper {
    monitor = HDMI-A-1
    path = /home/shadow_angel/Pictures/Wallpapers/wallpaper.jpg
    fit_mode = cover
}
splash = false
ipc = true
